# Markov chains computations

The goal of this notebook is to demonstrate some Python tools that can be useful in Markov chains computations.

In [3]:
import numpy as np

## Matrix addition/subtraction

Define a couple of matrices using `numpy`:

In [4]:
A = np.array([[1, 2, 3],
              [4, 3, 6],
              [7, 8, 9]])

B = np.array([[0, 1, 3],
              [2, 5, 2],
              [0, 0, 1]])

Addition of matrices:

In [5]:
A + B

array([[ 1,  3,  6],
       [ 6,  8,  8],
       [ 7,  8, 10]])

Subtraction: 

In [7]:
A - B

array([[ 1,  1,  0],
       [ 2, -2,  4],
       [ 7,  8,  8]])

## Matrix multiplication

Multiplication of a matrix by a scalar:

In [8]:
(1/2) * A 

array([[0.5, 1. , 1.5],
       [2. , 1.5, 3. ],
       [3.5, 4. , 4.5]])

Multiplication of a matrix by a vector:

In [9]:
v = np.array([1, 2, 3])
A @ v

array([14, 28, 50])

Multiplication of a matrix by a matrix:

In [10]:
A @ B

array([[ 4, 11, 10],
       [ 6, 19, 24],
       [16, 47, 46]])

## Matrix inverse

Compute the inverse of the matrix `A`:

In [11]:
np.linalg.inv(A)

array([[-0.875     ,  0.25      ,  0.125     ],
       [ 0.25      , -0.5       ,  0.25      ],
       [ 0.45833333,  0.25      , -0.20833333]])

**Note.** This function will give an error if used with a non-invertible matrix.

## The identity matrix

`np.eye` function gives an easy way of creating the identity matrix of a given size. For example, to get the 4x4 identity matrix we can use the folling: 

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])