# Matrix powers

The goal of this notebook is to show how to compute products of matrices and powers of matrices using Python. First, we import the `numpy` library, which provides tools for such computations:

In [1]:
import numpy as np

Next we define a couple matrices using `numpy`:

In [18]:
A = np.array([[1, 2, 3],
              [4, 3, 6],
              [7, 8, 9]])

B = np.array([[0, 1, 3],
              [2, 5, 2],
              [0, 0, 1]])

In [3]:
print(A)

[[1 2 3]
 [4 3 6]
 [7 8 9]]


In [4]:
print(B)

[[0 1 3]
 [2 5 2]
 [0 0 1]]


## Matrix multiplication

The operator `@` performs matrix multiplication:

In [5]:
A@B

array([[ 4, 11, 10],
       [ 6, 19, 24],
       [16, 47, 46]])

## Matrix powers

To take a power of a matrix we can multiply it by itself some number of times:

In [6]:
# compute the 4th power of A
A@A@A@A

array([[ 7040,  7660, 10248],
       [14078, 15321, 20496],
       [24740, 26914, 36024]])

However, it is simpler and faster to use the `np.linalg.matrix_power` function that it designed to compute a given power of a matrix:

In [7]:
# compute the 4th power of A
np.linalg.matrix_power(A, 4)

array([[ 7040,  7660, 10248],
       [14078, 15321, 20496],
       [24740, 26914, 36024]])

## Sum of entries of a matrix

Here is one more numpy computation that may come handy in Homework 4. If `A` is a numpy matrix then 
`A.sum()` computes the sum of all entries of `A`.

In [19]:
print(A)

[[1 2 3]
 [4 3 6]
 [7 8 9]]


In [20]:
A.sum()

43