# PCA computations

The goal of this notebook is to demonstrate some Python tools that can be useful in PCA computations.

## Matrix multiplication

In [1]:
import numpy as np

Define a couple of matrices using `numpy`:

In [2]:
A = np.array([[1, 2, 3],
              [4, 3, 6],
              [7, 8, 9]])

B = np.array([[0, 1, 3],
              [2, 5, 2],
              [0, 0, 1]])

Multiplication of a matrix by a scalar:

In [3]:
(1/2) * A 

array([[0.5, 1. , 1.5],
       [2. , 1.5, 3. ],
       [3.5, 4. , 4.5]])

Multiplication of a matrix by a vector:

In [4]:
v = np.array([1, 2, 3])
A @ v

array([14, 28, 50])

Multiplication of a matrix by a matrix:

In [5]:
A @ B

array([[ 4, 11, 10],
       [ 6, 19, 24],
       [16, 47, 46]])

## Matrix transpose

In [6]:
A.T

array([[1, 4, 7],
       [2, 3, 8],
       [3, 6, 9]])

## Trace of a matrix

In [7]:
np.trace(A)

13

## Computing eigenvalues and eigenvectors

Define a sample matrix:

In [8]:
C = np.array([[8, 2, 5, 8],
              [2, 9, 8, 5],
              [5, 8, 8, 9],
              [8, 5, 9, 8]])

The function `np.linalg.eig` returns a tuple giving eigenvalues and eigenvectors of a matrix:

In [9]:
eigenvals, eigenvects = np.linalg.eig(C)

Eigenvalues of the matrix `C`:

In [10]:
print(eigenvals)

[27.15475075  7.567203    0.33785338 -2.05980714]


`eigenvects` is as matrix of eigenvectors of `C` with each column giving one eigenvector:

In [11]:
print(eigenvects)

[[ 0.42453415  0.64417668  0.5774985   0.26702554]
 [ 0.44593734 -0.68865353  0.53436729 -0.2033416 ]
 [ 0.55832431 -0.202712   -0.48210397  0.64401676]
 [ 0.55604371  0.26400866 -0.38538662 -0.68745325]]


The first column of is an eigenvector corresponding to the first eigenvalue, the seconds columns is an eigenvector corresponding to the second eigenvalue etc. To verify, lets multiply the first column of `eigenvects` by the matrix `C`:

In [12]:
C @ eigenvects[:, 0]

array([11.52811913, 12.10931739, 15.16115735, 15.09922838])

Notice the result is the same as multiplying this columns by the first eigenvalue: 

In [13]:
eigenvals[0]*eigenvects[:, 0]

array([11.52811913, 12.10931739, 15.16115735, 15.09922838])

**Note** All eigenvectors returned by `np.linalg.eig` are vectors of length 1. 